export const TasksAction = {
  GET_ALL_TASKS: "GET_ALL_TASKS",
  GET_ALL_ASSIGNED_USERS: "GET_ALL_ASSIGNED_USERS",
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
};
